/**
 * Visual-regression parity check: the PDF generated by the invoice preview
 * dialog ("Download PDF") must render identically to the PDF sent as an
 * email attachment.
 *
 * Both PDFs are produced by different code paths:
 *  - preview download → clones the on-screen <InvoiceTemplate> DOM and
 *    rasterises it via html2canvas-pro + jsPDF (invoice-preview-dialog.tsx).
 *  - email attachment → mounts a fresh <InvoiceTemplate> off-screen and
 *    rasterises it the same way (src/lib/render-invoice-template-pdf.tsx).
 *
 * We expose both renderers on `window.__invoicePdfTest` in dev mode, call
 * them from the same page, and pixel-compare the resulting PDFs page-by-page.
 * Any color/layout drift between the two paths fails this test.
 *
 * Configuration:
 *   TEST_INVOICE_ID       specific invoice UUID (else: first from list)
 *   PDF_DIFF_THRESHOLD    max diff-pixel ratio per page (default 0.005)
 *   PDF_DPI               raster density (default 150)
 */
import { test, expect } from "@playwright/test";
import { promises as fs } from "node:fs";
import path from "node:path";
import pixelmatch from "pixelmatch";
import { PNG } from "pngjs";
import { pdfToPngPages, decodePng } from "./helpers/pdf-to-png";

const ARTIFACT_DIR = path.resolve(process.cwd(), "tests/visual/__artifacts__/invoice-pdf");
const DIFF_THRESHOLD = Number(process.env.PDF_DIFF_THRESHOLD ?? "0.005");
const PDF_DPI = Number(process.env.PDF_DPI ?? "150");

// Reuse the auth-restore logic from the browser-use guide. Kept inline so
// this spec has no cross-test coupling.
async function restoreSupabaseSession(context: import("@playwright/test").BrowserContext, page: import("@playwright/test").Page) {
  const cookiesJson = process.env.LOVABLE_BROWSER_SUPABASE_COOKIES_JSON;
  const storageKey = process.env.LOVABLE_BROWSER_SUPABASE_STORAGE_KEY;
  const sessionJson = process.env.LOVABLE_BROWSER_SUPABASE_SESSION_JSON;

  if (cookiesJson) {
    const parsed = JSON.parse(cookiesJson) as Array<Record<string, unknown>>;
    for (const c of parsed) c.url = "http://localhost:8080";
    // @ts-expect-error — cookie shape validated by Playwright at runtime
    await context.addCookies(parsed);
  }

  await page.goto("http://localhost:8080");

  if (storageKey && sessionJson) {
    await page.evaluate(
      ([k, v]) => {
        window.localStorage.setItem(k, v);
      },
      [storageKey, sessionJson] as const,
    );
  }
}

async function readInvoicePdfBlobs(
  page: import("@playwright/test").Page,
): Promise<{ preview: Buffer; email: Buffer }> {
  // Open the preview dialog so `renderPreview` mounts on window.
  await page.getByRole("button", { name: /^voorbeeld$/i }).click().catch(async () => {
    // Some layouts label it "Preview" or use an icon-only button — try aria.
    await page.getByRole("button", { name: /preview|voorbeeld/i }).first().click();
  });

  // Wait for both hooks to be present.
  await page.waitForFunction(
    () => {
      const g = window as unknown as {
        __invoicePdfTest?: { renderPreview?: unknown; renderEmail?: unknown };
      };
      return !!g.__invoicePdfTest?.renderPreview && !!g.__invoicePdfTest?.renderEmail;
    },
    { timeout: 15_000 },
  );

  // Render both PDFs and stream them out as base64.
  const [previewB64, emailB64] = await page.evaluate(async () => {
    const g = window as unknown as {
      __invoicePdfTest: {
        renderPreview: () => Promise<Blob>;
        renderEmail: () => Promise<Blob>;
      };
    };
    async function toB64(blob: Blob): Promise<string> {
      const buf = await blob.arrayBuffer();
      // Chunked base64 to avoid stack overflow on large buffers.
      const bytes = new Uint8Array(buf);
      let bin = "";
      const chunk = 0x8000;
      for (let i = 0; i < bytes.length; i += chunk) {
        bin += String.fromCharCode.apply(
          null,
          Array.from(bytes.subarray(i, i + chunk)),
        );
      }
      return btoa(bin);
    }
    const p = await g.__invoicePdfTest.renderPreview();
    const e = await g.__invoicePdfTest.renderEmail();
    return [await toB64(p), await toB64(e)];
  });

  return {
    preview: Buffer.from(previewB64, "base64"),
    email: Buffer.from(emailB64, "base64"),
  };
}

async function ensureArtifactDir() {
  await fs.mkdir(ARTIFACT_DIR, { recursive: true });
}

async function writeArtifact(name: string, buf: Buffer) {
  await ensureArtifactDir();
  await fs.writeFile(path.join(ARTIFACT_DIR, name), buf);
}

test.describe("Invoice PDF parity — preview download vs email attachment", () => {
  test("renders identical pages within tolerance", async ({ context, page }) => {
    test.setTimeout(180_000);

    await restoreSupabaseSession(context, page);

    // Pick target invoice.
    const invoiceId = process.env.TEST_INVOICE_ID;
    if (invoiceId) {
      await page.goto(`http://localhost:8080/invoices/${invoiceId}`);
    } else {
      await page.goto("http://localhost:8080/invoices");
      // Click first invoice row link.
      await page.locator('a[href*="/invoices/"]').first().click();
    }
    await page.waitForLoadState("networkidle");

    const { preview, email } = await readInvoicePdfBlobs(page);

    // Persist raw PDFs for post-mortem regardless of pass/fail.
    await writeArtifact("preview.pdf", preview);
    await writeArtifact("email.pdf", email);

    const [previewPages, emailPages] = await Promise.all([
      pdfToPngPages(new Uint8Array(preview), { dpi: PDF_DPI }),
      pdfToPngPages(new Uint8Array(email), { dpi: PDF_DPI }),
    ]);

    expect(previewPages.length, "page count must match").toBe(emailPages.length);

    const failures: string[] = [];
    for (let i = 0; i < previewPages.length; i += 1) {
      const a = decodePng(previewPages[i].buffer);
      const b = decodePng(emailPages[i].buffer);

      if (a.width !== b.width || a.height !== b.height) {
        await writeArtifact(`preview-page-${i + 1}.png`, previewPages[i].buffer);
        await writeArtifact(`email-page-${i + 1}.png`, emailPages[i].buffer);
        failures.push(
          `page ${i + 1}: dimensions differ (preview ${a.width}x${a.height} vs email ${b.width}x${b.height})`,
        );
        continue;
      }

      const diff = new PNG({ width: a.width, height: a.height });
      const changed = pixelmatch(a.data, b.data, diff.data, a.width, a.height, {
        threshold: 0.1,
        includeAA: false,
      });
      const total = a.width * a.height;
      const ratio = changed / total;

      if (ratio > DIFF_THRESHOLD) {
        await writeArtifact(`preview-page-${i + 1}.png`, previewPages[i].buffer);
        await writeArtifact(`email-page-${i + 1}.png`, emailPages[i].buffer);
        await writeArtifact(`diff-page-${i + 1}.png`, PNG.sync.write(diff));
        failures.push(
          `page ${i + 1}: ${changed}/${total} pixels differ (${(ratio * 100).toFixed(3)}% > ${(DIFF_THRESHOLD * 100).toFixed(3)}%)`,
        );
      }
    }

    if (failures.length > 0) {
      throw new Error(
        `PDF parity check failed:\n  - ${failures.join("\n  - ")}\nArtifacts saved to ${ARTIFACT_DIR}`,
      );
    }
  });
});
