/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedProductenRouteImport } from './routes/_authenticated/producten'
import { Route as AuthenticatedNetqloudRouteImport } from './routes/_authenticated/netqloud'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedGebruikersRouteImport } from './routes/_authenticated/gebruikers'
import { Route as AuthenticatedBoekhoudingRouteImport } from './routes/_authenticated/boekhouding'
import { Route as AuthenticatedAiColumbusRouteImport } from './routes/_authenticated/ai-columbus'
import { Route as AuthenticatedAdministratieRouteImport } from './routes/_authenticated/administratie'
import { Route as AuthenticatedNetqloudIndexRouteImport } from './routes/_authenticated/netqloud.index'
import { Route as AuthenticatedAiColumbusIndexRouteImport } from './routes/_authenticated/ai-columbus.index'
import { Route as AcceptQuoteTokenRouteImport } from './routes/accept.quote.$token'
import { Route as AuthenticatedNetqloudServersRouteImport } from './routes/_authenticated/netqloud.servers'
import { Route as AuthenticatedNetqloudKlantenRouteImport } from './routes/_authenticated/netqloud.klanten'
import { Route as AuthenticatedNetqloudInstellingenRouteImport } from './routes/_authenticated/netqloud.instellingen'
import { Route as AuthenticatedAiColumbusRapportagesRouteImport } from './routes/_authenticated/ai-columbus.rapportages'
import { Route as AuthenticatedAiColumbusProjectenRouteImport } from './routes/_authenticated/ai-columbus.projecten'
import { Route as AuthenticatedAiColumbusModellenRouteImport } from './routes/_authenticated/ai-columbus.modellen'
import { Route as AuthenticatedAiColumbusLogsRouteImport } from './routes/_authenticated/ai-columbus.logs'
import { Route as AuthenticatedAiColumbusLeadsRouteImport } from './routes/_authenticated/ai-columbus.leads'
import { Route as AuthenticatedAiColumbusKlantenRouteImport } from './routes/_authenticated/ai-columbus.klanten'
import { Route as AuthenticatedAiColumbusInstellingenRouteImport } from './routes/_authenticated/ai-columbus.instellingen'
import { Route as AuthenticatedBoekhoudingJournalEntryIdRouteImport } from './routes/_authenticated/boekhouding.journal.$entryId'
import { Route as AuthenticatedAiColumbusProjectenProjectIdRouteImport } from './routes/_authenticated/ai-columbus.projecten.$projectId'
import { Route as AuthenticatedAiColumbusKlantenClientIdRouteImport } from './routes/_authenticated/ai-columbus.klanten.$clientId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductenRoute = AuthenticatedProductenRouteImport.update({
  id: '/producten',
  path: '/producten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetqloudRoute = AuthenticatedNetqloudRouteImport.update({
  id: '/netqloud',
  path: '/netqloud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGebruikersRoute = AuthenticatedGebruikersRouteImport.update({
  id: '/gebruikers',
  path: '/gebruikers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoekhoudingRoute =
  AuthenticatedBoekhoudingRouteImport.update({
    id: '/boekhouding',
    path: '/boekhouding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiColumbusRoute = AuthenticatedAiColumbusRouteImport.update({
  id: '/ai-columbus',
  path: '/ai-columbus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministratieRoute =
  AuthenticatedAdministratieRouteImport.update({
    id: '/administratie',
    path: '/administratie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNetqloudIndexRoute =
  AuthenticatedNetqloudIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNetqloudRoute,
  } as any)
const AuthenticatedAiColumbusIndexRoute =
  AuthenticatedAiColumbusIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AcceptQuoteTokenRoute = AcceptQuoteTokenRouteImport.update({
  id: '/accept/quote/$token',
  path: '/accept/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNetqloudServersRoute =
  AuthenticatedNetqloudServersRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => AuthenticatedNetqloudRoute,
  } as any)
const AuthenticatedNetqloudKlantenRoute =
  AuthenticatedNetqloudKlantenRouteImport.update({
    id: '/klanten',
    path: '/klanten',
    getParentRoute: () => AuthenticatedNetqloudRoute,
  } as any)
const AuthenticatedNetqloudInstellingenRoute =
  AuthenticatedNetqloudInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedNetqloudRoute,
  } as any)
const AuthenticatedAiColumbusRapportagesRoute =
  AuthenticatedAiColumbusRapportagesRouteImport.update({
    id: '/rapportages',
    path: '/rapportages',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusProjectenRoute =
  AuthenticatedAiColumbusProjectenRouteImport.update({
    id: '/projecten',
    path: '/projecten',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusModellenRoute =
  AuthenticatedAiColumbusModellenRouteImport.update({
    id: '/modellen',
    path: '/modellen',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusLogsRoute =
  AuthenticatedAiColumbusLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusLeadsRoute =
  AuthenticatedAiColumbusLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusKlantenRoute =
  AuthenticatedAiColumbusKlantenRouteImport.update({
    id: '/klanten',
    path: '/klanten',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedAiColumbusInstellingenRoute =
  AuthenticatedAiColumbusInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedAiColumbusRoute,
  } as any)
const AuthenticatedBoekhoudingJournalEntryIdRoute =
  AuthenticatedBoekhoudingJournalEntryIdRouteImport.update({
    id: '/journal/$entryId',
    path: '/journal/$entryId',
    getParentRoute: () => AuthenticatedBoekhoudingRoute,
  } as any)
const AuthenticatedAiColumbusProjectenProjectIdRoute =
  AuthenticatedAiColumbusProjectenProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedAiColumbusProjectenRoute,
  } as any)
const AuthenticatedAiColumbusKlantenClientIdRoute =
  AuthenticatedAiColumbusKlantenClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAiColumbusKlantenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administratie': typeof AuthenticatedAdministratieRoute
  '/ai-columbus': typeof AuthenticatedAiColumbusRouteWithChildren
  '/boekhouding': typeof AuthenticatedBoekhoudingRouteWithChildren
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/netqloud': typeof AuthenticatedNetqloudRouteWithChildren
  '/producten': typeof AuthenticatedProductenRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/ai-columbus/instellingen': typeof AuthenticatedAiColumbusInstellingenRoute
  '/ai-columbus/klanten': typeof AuthenticatedAiColumbusKlantenRouteWithChildren
  '/ai-columbus/leads': typeof AuthenticatedAiColumbusLeadsRoute
  '/ai-columbus/logs': typeof AuthenticatedAiColumbusLogsRoute
  '/ai-columbus/modellen': typeof AuthenticatedAiColumbusModellenRoute
  '/ai-columbus/projecten': typeof AuthenticatedAiColumbusProjectenRouteWithChildren
  '/ai-columbus/rapportages': typeof AuthenticatedAiColumbusRapportagesRoute
  '/netqloud/instellingen': typeof AuthenticatedNetqloudInstellingenRoute
  '/netqloud/klanten': typeof AuthenticatedNetqloudKlantenRoute
  '/netqloud/servers': typeof AuthenticatedNetqloudServersRoute
  '/accept/quote/$token': typeof AcceptQuoteTokenRoute
  '/ai-columbus/': typeof AuthenticatedAiColumbusIndexRoute
  '/netqloud/': typeof AuthenticatedNetqloudIndexRoute
  '/ai-columbus/klanten/$clientId': typeof AuthenticatedAiColumbusKlantenClientIdRoute
  '/ai-columbus/projecten/$projectId': typeof AuthenticatedAiColumbusProjectenProjectIdRoute
  '/boekhouding/journal/$entryId': typeof AuthenticatedBoekhoudingJournalEntryIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administratie': typeof AuthenticatedAdministratieRoute
  '/boekhouding': typeof AuthenticatedBoekhoudingRouteWithChildren
  '/gebruikers': typeof AuthenticatedGebruikersRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/producten': typeof AuthenticatedProductenRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/': typeof AuthenticatedIndexRoute
  '/ai-columbus/instellingen': typeof AuthenticatedAiColumbusInstellingenRoute
  '/ai-columbus/klanten': typeof AuthenticatedAiColumbusKlantenRouteWithChildren
  '/ai-columbus/leads': typeof AuthenticatedAiColumbusLeadsRoute
  '/ai-columbus/logs': typeof AuthenticatedAiColumbusLogsRoute
  '/ai-columbus/modellen': typeof AuthenticatedAiColumbusModellenRoute
  '/ai-columbus/projecten': typeof AuthenticatedAiColumbusProjectenRouteWithChildren
  '/ai-columbus/rapportages': typeof AuthenticatedAiColumbusRapportagesRoute
  '/netqloud/instellingen': typeof AuthenticatedNetqloudInstellingenRoute
  '/netqloud/klanten': typeof AuthenticatedNetqloudKlantenRoute
  '/netqloud/servers': typeof AuthenticatedNetqloudServersRoute
  '/accept/quote/$token': typeof AcceptQuoteTokenRoute
  '/ai-columbus': typeof AuthenticatedAiColumbusIndexRoute
  '/netqloud': typeof AuthenticatedNetqloudIndexRoute
  '/ai-columbus/klanten/$clientId': typeof AuthenticatedAiColumbusKlantenClientIdRoute
  '/ai-columbus/projecten/$projectId': typeof AuthenticatedAiColumbusProjectenProjectIdRoute
  '/boekhouding/journal/$entryId': typeof AuthenticatedBoekhoudingJournalEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administratie': typeof AuthenticatedAdministratieRoute
  '/_authenticated/ai-columbus': typeof AuthenticatedAiColumbusRouteWithChildren
  '/_authenticated/boekhouding': typeof AuthenticatedBoekhoudingRouteWithChildren
  '/_authenticated/gebruikers': typeof AuthenticatedGebruikersRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/netqloud': typeof AuthenticatedNetqloudRouteWithChildren
  '/_authenticated/producten': typeof AuthenticatedProductenRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ai-columbus/instellingen': typeof AuthenticatedAiColumbusInstellingenRoute
  '/_authenticated/ai-columbus/klanten': typeof AuthenticatedAiColumbusKlantenRouteWithChildren
  '/_authenticated/ai-columbus/leads': typeof AuthenticatedAiColumbusLeadsRoute
  '/_authenticated/ai-columbus/logs': typeof AuthenticatedAiColumbusLogsRoute
  '/_authenticated/ai-columbus/modellen': typeof AuthenticatedAiColumbusModellenRoute
  '/_authenticated/ai-columbus/projecten': typeof AuthenticatedAiColumbusProjectenRouteWithChildren
  '/_authenticated/ai-columbus/rapportages': typeof AuthenticatedAiColumbusRapportagesRoute
  '/_authenticated/netqloud/instellingen': typeof AuthenticatedNetqloudInstellingenRoute
  '/_authenticated/netqloud/klanten': typeof AuthenticatedNetqloudKlantenRoute
  '/_authenticated/netqloud/servers': typeof AuthenticatedNetqloudServersRoute
  '/accept/quote/$token': typeof AcceptQuoteTokenRoute
  '/_authenticated/ai-columbus/': typeof AuthenticatedAiColumbusIndexRoute
  '/_authenticated/netqloud/': typeof AuthenticatedNetqloudIndexRoute
  '/_authenticated/ai-columbus/klanten/$clientId': typeof AuthenticatedAiColumbusKlantenClientIdRoute
  '/_authenticated/ai-columbus/projecten/$projectId': typeof AuthenticatedAiColumbusProjectenProjectIdRoute
  '/_authenticated/boekhouding/journal/$entryId': typeof AuthenticatedBoekhoudingJournalEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administratie'
    | '/ai-columbus'
    | '/boekhouding'
    | '/gebruikers'
    | '/invoices'
    | '/netqloud'
    | '/producten'
    | '/quotes'
    | '/teams'
    | '/ai-columbus/instellingen'
    | '/ai-columbus/klanten'
    | '/ai-columbus/leads'
    | '/ai-columbus/logs'
    | '/ai-columbus/modellen'
    | '/ai-columbus/projecten'
    | '/ai-columbus/rapportages'
    | '/netqloud/instellingen'
    | '/netqloud/klanten'
    | '/netqloud/servers'
    | '/accept/quote/$token'
    | '/ai-columbus/'
    | '/netqloud/'
    | '/ai-columbus/klanten/$clientId'
    | '/ai-columbus/projecten/$projectId'
    | '/boekhouding/journal/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/administratie'
    | '/boekhouding'
    | '/gebruikers'
    | '/invoices'
    | '/producten'
    | '/quotes'
    | '/teams'
    | '/'
    | '/ai-columbus/instellingen'
    | '/ai-columbus/klanten'
    | '/ai-columbus/leads'
    | '/ai-columbus/logs'
    | '/ai-columbus/modellen'
    | '/ai-columbus/projecten'
    | '/ai-columbus/rapportages'
    | '/netqloud/instellingen'
    | '/netqloud/klanten'
    | '/netqloud/servers'
    | '/accept/quote/$token'
    | '/ai-columbus'
    | '/netqloud'
    | '/ai-columbus/klanten/$clientId'
    | '/ai-columbus/projecten/$projectId'
    | '/boekhouding/journal/$entryId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administratie'
    | '/_authenticated/ai-columbus'
    | '/_authenticated/boekhouding'
    | '/_authenticated/gebruikers'
    | '/_authenticated/invoices'
    | '/_authenticated/netqloud'
    | '/_authenticated/producten'
    | '/_authenticated/quotes'
    | '/_authenticated/teams'
    | '/_authenticated/'
    | '/_authenticated/ai-columbus/instellingen'
    | '/_authenticated/ai-columbus/klanten'
    | '/_authenticated/ai-columbus/leads'
    | '/_authenticated/ai-columbus/logs'
    | '/_authenticated/ai-columbus/modellen'
    | '/_authenticated/ai-columbus/projecten'
    | '/_authenticated/ai-columbus/rapportages'
    | '/_authenticated/netqloud/instellingen'
    | '/_authenticated/netqloud/klanten'
    | '/_authenticated/netqloud/servers'
    | '/accept/quote/$token'
    | '/_authenticated/ai-columbus/'
    | '/_authenticated/netqloud/'
    | '/_authenticated/ai-columbus/klanten/$clientId'
    | '/_authenticated/ai-columbus/projecten/$projectId'
    | '/_authenticated/boekhouding/journal/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AcceptQuoteTokenRoute: typeof AcceptQuoteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producten': {
      id: '/_authenticated/producten'
      path: '/producten'
      fullPath: '/producten'
      preLoaderRoute: typeof AuthenticatedProductenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/netqloud': {
      id: '/_authenticated/netqloud'
      path: '/netqloud'
      fullPath: '/netqloud'
      preLoaderRoute: typeof AuthenticatedNetqloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gebruikers': {
      id: '/_authenticated/gebruikers'
      path: '/gebruikers'
      fullPath: '/gebruikers'
      preLoaderRoute: typeof AuthenticatedGebruikersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boekhouding': {
      id: '/_authenticated/boekhouding'
      path: '/boekhouding'
      fullPath: '/boekhouding'
      preLoaderRoute: typeof AuthenticatedBoekhoudingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-columbus': {
      id: '/_authenticated/ai-columbus'
      path: '/ai-columbus'
      fullPath: '/ai-columbus'
      preLoaderRoute: typeof AuthenticatedAiColumbusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administratie': {
      id: '/_authenticated/administratie'
      path: '/administratie'
      fullPath: '/administratie'
      preLoaderRoute: typeof AuthenticatedAdministratieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/netqloud/': {
      id: '/_authenticated/netqloud/'
      path: '/'
      fullPath: '/netqloud/'
      preLoaderRoute: typeof AuthenticatedNetqloudIndexRouteImport
      parentRoute: typeof AuthenticatedNetqloudRoute
    }
    '/_authenticated/ai-columbus/': {
      id: '/_authenticated/ai-columbus/'
      path: '/'
      fullPath: '/ai-columbus/'
      preLoaderRoute: typeof AuthenticatedAiColumbusIndexRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/accept/quote/$token': {
      id: '/accept/quote/$token'
      path: '/accept/quote/$token'
      fullPath: '/accept/quote/$token'
      preLoaderRoute: typeof AcceptQuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/netqloud/servers': {
      id: '/_authenticated/netqloud/servers'
      path: '/servers'
      fullPath: '/netqloud/servers'
      preLoaderRoute: typeof AuthenticatedNetqloudServersRouteImport
      parentRoute: typeof AuthenticatedNetqloudRoute
    }
    '/_authenticated/netqloud/klanten': {
      id: '/_authenticated/netqloud/klanten'
      path: '/klanten'
      fullPath: '/netqloud/klanten'
      preLoaderRoute: typeof AuthenticatedNetqloudKlantenRouteImport
      parentRoute: typeof AuthenticatedNetqloudRoute
    }
    '/_authenticated/netqloud/instellingen': {
      id: '/_authenticated/netqloud/instellingen'
      path: '/instellingen'
      fullPath: '/netqloud/instellingen'
      preLoaderRoute: typeof AuthenticatedNetqloudInstellingenRouteImport
      parentRoute: typeof AuthenticatedNetqloudRoute
    }
    '/_authenticated/ai-columbus/rapportages': {
      id: '/_authenticated/ai-columbus/rapportages'
      path: '/rapportages'
      fullPath: '/ai-columbus/rapportages'
      preLoaderRoute: typeof AuthenticatedAiColumbusRapportagesRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/projecten': {
      id: '/_authenticated/ai-columbus/projecten'
      path: '/projecten'
      fullPath: '/ai-columbus/projecten'
      preLoaderRoute: typeof AuthenticatedAiColumbusProjectenRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/modellen': {
      id: '/_authenticated/ai-columbus/modellen'
      path: '/modellen'
      fullPath: '/ai-columbus/modellen'
      preLoaderRoute: typeof AuthenticatedAiColumbusModellenRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/logs': {
      id: '/_authenticated/ai-columbus/logs'
      path: '/logs'
      fullPath: '/ai-columbus/logs'
      preLoaderRoute: typeof AuthenticatedAiColumbusLogsRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/leads': {
      id: '/_authenticated/ai-columbus/leads'
      path: '/leads'
      fullPath: '/ai-columbus/leads'
      preLoaderRoute: typeof AuthenticatedAiColumbusLeadsRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/klanten': {
      id: '/_authenticated/ai-columbus/klanten'
      path: '/klanten'
      fullPath: '/ai-columbus/klanten'
      preLoaderRoute: typeof AuthenticatedAiColumbusKlantenRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/ai-columbus/instellingen': {
      id: '/_authenticated/ai-columbus/instellingen'
      path: '/instellingen'
      fullPath: '/ai-columbus/instellingen'
      preLoaderRoute: typeof AuthenticatedAiColumbusInstellingenRouteImport
      parentRoute: typeof AuthenticatedAiColumbusRoute
    }
    '/_authenticated/boekhouding/journal/$entryId': {
      id: '/_authenticated/boekhouding/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/boekhouding/journal/$entryId'
      preLoaderRoute: typeof AuthenticatedBoekhoudingJournalEntryIdRouteImport
      parentRoute: typeof AuthenticatedBoekhoudingRoute
    }
    '/_authenticated/ai-columbus/projecten/$projectId': {
      id: '/_authenticated/ai-columbus/projecten/$projectId'
      path: '/$projectId'
      fullPath: '/ai-columbus/projecten/$projectId'
      preLoaderRoute: typeof AuthenticatedAiColumbusProjectenProjectIdRouteImport
      parentRoute: typeof AuthenticatedAiColumbusProjectenRoute
    }
    '/_authenticated/ai-columbus/klanten/$clientId': {
      id: '/_authenticated/ai-columbus/klanten/$clientId'
      path: '/$clientId'
      fullPath: '/ai-columbus/klanten/$clientId'
      preLoaderRoute: typeof AuthenticatedAiColumbusKlantenClientIdRouteImport
      parentRoute: typeof AuthenticatedAiColumbusKlantenRoute
    }
  }
}

interface AuthenticatedAiColumbusKlantenRouteChildren {
  AuthenticatedAiColumbusKlantenClientIdRoute: typeof AuthenticatedAiColumbusKlantenClientIdRoute
}

const AuthenticatedAiColumbusKlantenRouteChildren: AuthenticatedAiColumbusKlantenRouteChildren =
  {
    AuthenticatedAiColumbusKlantenClientIdRoute:
      AuthenticatedAiColumbusKlantenClientIdRoute,
  }

const AuthenticatedAiColumbusKlantenRouteWithChildren =
  AuthenticatedAiColumbusKlantenRoute._addFileChildren(
    AuthenticatedAiColumbusKlantenRouteChildren,
  )

interface AuthenticatedAiColumbusProjectenRouteChildren {
  AuthenticatedAiColumbusProjectenProjectIdRoute: typeof AuthenticatedAiColumbusProjectenProjectIdRoute
}

const AuthenticatedAiColumbusProjectenRouteChildren: AuthenticatedAiColumbusProjectenRouteChildren =
  {
    AuthenticatedAiColumbusProjectenProjectIdRoute:
      AuthenticatedAiColumbusProjectenProjectIdRoute,
  }

const AuthenticatedAiColumbusProjectenRouteWithChildren =
  AuthenticatedAiColumbusProjectenRoute._addFileChildren(
    AuthenticatedAiColumbusProjectenRouteChildren,
  )

interface AuthenticatedAiColumbusRouteChildren {
  AuthenticatedAiColumbusInstellingenRoute: typeof AuthenticatedAiColumbusInstellingenRoute
  AuthenticatedAiColumbusKlantenRoute: typeof AuthenticatedAiColumbusKlantenRouteWithChildren
  AuthenticatedAiColumbusLeadsRoute: typeof AuthenticatedAiColumbusLeadsRoute
  AuthenticatedAiColumbusLogsRoute: typeof AuthenticatedAiColumbusLogsRoute
  AuthenticatedAiColumbusModellenRoute: typeof AuthenticatedAiColumbusModellenRoute
  AuthenticatedAiColumbusProjectenRoute: typeof AuthenticatedAiColumbusProjectenRouteWithChildren
  AuthenticatedAiColumbusRapportagesRoute: typeof AuthenticatedAiColumbusRapportagesRoute
  AuthenticatedAiColumbusIndexRoute: typeof AuthenticatedAiColumbusIndexRoute
}

const AuthenticatedAiColumbusRouteChildren: AuthenticatedAiColumbusRouteChildren =
  {
    AuthenticatedAiColumbusInstellingenRoute:
      AuthenticatedAiColumbusInstellingenRoute,
    AuthenticatedAiColumbusKlantenRoute:
      AuthenticatedAiColumbusKlantenRouteWithChildren,
    AuthenticatedAiColumbusLeadsRoute: AuthenticatedAiColumbusLeadsRoute,
    AuthenticatedAiColumbusLogsRoute: AuthenticatedAiColumbusLogsRoute,
    AuthenticatedAiColumbusModellenRoute: AuthenticatedAiColumbusModellenRoute,
    AuthenticatedAiColumbusProjectenRoute:
      AuthenticatedAiColumbusProjectenRouteWithChildren,
    AuthenticatedAiColumbusRapportagesRoute:
      AuthenticatedAiColumbusRapportagesRoute,
    AuthenticatedAiColumbusIndexRoute: AuthenticatedAiColumbusIndexRoute,
  }

const AuthenticatedAiColumbusRouteWithChildren =
  AuthenticatedAiColumbusRoute._addFileChildren(
    AuthenticatedAiColumbusRouteChildren,
  )

interface AuthenticatedBoekhoudingRouteChildren {
  AuthenticatedBoekhoudingJournalEntryIdRoute: typeof AuthenticatedBoekhoudingJournalEntryIdRoute
}

const AuthenticatedBoekhoudingRouteChildren: AuthenticatedBoekhoudingRouteChildren =
  {
    AuthenticatedBoekhoudingJournalEntryIdRoute:
      AuthenticatedBoekhoudingJournalEntryIdRoute,
  }

const AuthenticatedBoekhoudingRouteWithChildren =
  AuthenticatedBoekhoudingRoute._addFileChildren(
    AuthenticatedBoekhoudingRouteChildren,
  )

interface AuthenticatedNetqloudRouteChildren {
  AuthenticatedNetqloudInstellingenRoute: typeof AuthenticatedNetqloudInstellingenRoute
  AuthenticatedNetqloudKlantenRoute: typeof AuthenticatedNetqloudKlantenRoute
  AuthenticatedNetqloudServersRoute: typeof AuthenticatedNetqloudServersRoute
  AuthenticatedNetqloudIndexRoute: typeof AuthenticatedNetqloudIndexRoute
}

const AuthenticatedNetqloudRouteChildren: AuthenticatedNetqloudRouteChildren = {
  AuthenticatedNetqloudInstellingenRoute:
    AuthenticatedNetqloudInstellingenRoute,
  AuthenticatedNetqloudKlantenRoute: AuthenticatedNetqloudKlantenRoute,
  AuthenticatedNetqloudServersRoute: AuthenticatedNetqloudServersRoute,
  AuthenticatedNetqloudIndexRoute: AuthenticatedNetqloudIndexRoute,
}

const AuthenticatedNetqloudRouteWithChildren =
  AuthenticatedNetqloudRoute._addFileChildren(
    AuthenticatedNetqloudRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministratieRoute: typeof AuthenticatedAdministratieRoute
  AuthenticatedAiColumbusRoute: typeof AuthenticatedAiColumbusRouteWithChildren
  AuthenticatedBoekhoudingRoute: typeof AuthenticatedBoekhoudingRouteWithChildren
  AuthenticatedGebruikersRoute: typeof AuthenticatedGebruikersRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedNetqloudRoute: typeof AuthenticatedNetqloudRouteWithChildren
  AuthenticatedProductenRoute: typeof AuthenticatedProductenRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministratieRoute: AuthenticatedAdministratieRoute,
  AuthenticatedAiColumbusRoute: AuthenticatedAiColumbusRouteWithChildren,
  AuthenticatedBoekhoudingRoute: AuthenticatedBoekhoudingRouteWithChildren,
  AuthenticatedGebruikersRoute: AuthenticatedGebruikersRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedNetqloudRoute: AuthenticatedNetqloudRouteWithChildren,
  AuthenticatedProductenRoute: AuthenticatedProductenRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AcceptQuoteTokenRoute: AcceptQuoteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
